data:
  raw_dataset: "data\\raw\\data.csv"
  preprocessed_dataset: "data\\processed"

models:
  base_model: "distilbert-base-uncased"
  fine_tuned_model: "models\\Fine-tuned-model"

training_args:
  output_dir: "models"
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  learning_rate: 2e-5
  weight_decay: 0.01
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  load_best_model_at_end: True
